<template>
  <UContainer
    as="footer"
    class="py-3 border-t border-default text-center space-x-1"
  >
    <UButton
      icon="i-simple-icons-github"
      variant="ghost"
      size="lg"
      square
      to="https://github.com/M4gie"
    />
    <UButton
      icon="i-simple-icons-linkedin"
      variant="ghost"
      size="lg"
      square
      to="https://www.linkedin.com/in/steeven-regnault/"
    />
    <UButton
      icon="i-heroicons-envelope"
      variant="ghost"
      size="lg"
      square
      to="mailto:steeven.regnault+blog@pm.me"
    />
  </UContainer>
</template>
